---
title: "README"
author: "Chris Alley"
date: "5/2/2017"
output: html_document
---

# Coursera: Getting & Cleaning Data Course Project

## Project Purpose
The purpose of this project gather data from a given dataset and prepare a tidy dataset to be used for later analysis.

## Contents
* `README.Rmd`- Contents of repository & brief description of analysis

* `codebook.Rmd`- Description of variables associated with the dataset

* `run_analysis.R`- R script file used to create tidy dataset.

* `subjectActivityMean.csv`- Output file created by `run_analysis.R`

## Dataset Description & Source
The dataset used for this project represents data collected from Samsung Galaxy 5 smartphone accelerometers.  A full description of this dataset can be found at:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

The dataset used for this project can be found at:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## Output File Description
The output file is a summary of the mean and standard deviation measurements described within `codebook.Rmd` for each subject for each of the following activities:

1. Walking
2. Walking upstairs
3. Walking downstairs
4. Sitting
5. Standing
6. Laying

## Getting Started

1. Read thru the [codebook](codebook.Rmd) and the [run_analysis.R](run_analysis.R) script to get an understanding of the measurements associated with the output file as well as the steps taken within the script to create it.
2. Set your working directory for the project. The script will create a directory called `projectData` to download the data and extract it to a subdirectory called `UCA HAR Dataset`.
3. Run the `run_analysis.R` script.


